spring:
  application:
    name: NotificacaoApp

cloud:
  aws:
    region:
      static: sa-east-1
sqs:
  queue:
    url: https://sqs.sa-east-1.amazonaws.com/024848463050/notifications.fifo
s3:
  bucket-name: "notifications-bucket-123"
  region: "sa-east-1"
